### PR TITLE
LPS-100997 Fix usages

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:stop

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
@vicnate5 Can you help me look at this failure? It is unique, but it is weird, there is a failure on an upgrade to AssetEntry that happens way before anything that I touch, as far as I can tell. Thanks
https://testray.liferay.com/home/-/testray/case_results/878478520

**Comment by vicnate5** [comment]
@stsquared99 Not related. Random issue with the indexer.

**Pull request closed without merging**
