### PR TITLE
LPS-142505 Fail to view published publications changes

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:test:publications

**Comment by suilin** [comment]
Hi @stsquared99, due to the results are blocked by LRQA-71673, I cherry-pick your commit and run on https://github.com/suilin/liferay-portal/pull/470.

**Comment by xbrianlee** [comment]
ci:close

This change has been merged in https://github.com/brianchandotcom/liferay-portal/pull/109937.

**Pull request closed without merging**
