### PR TITLE
LPS-116380 Make Segments change tracking enabled

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:stop

**Comment by stsquared99** [comment]
ci:stop

**Comment by stsquared99** [comment]
ci:test

**Comment by vicnate5** [comment]
@stsquared99 The only unique failures here are with Depot, but the failures are all from the same CI slave - something likely went wrong there. The Depot tests that ran on another slave passed, so this should be good.

If you have this branch running locally, you can double check with the following steps:
# Go to Global Menu > Asset Libraries
# Add a new Asset Library > Save
# Navigate to http://localhost:8080/group/control_panel/manage?p_p_id=com_liferay_depot_web_portlet_DepotAdminPortlet
# Assert the created Asset Library is present

**Comment by stsquared99** [comment]
@vicnate5 Checked out. Thanks!

**Pull request closed without merging**
