### PR TITLE
LPS-86798 Error message when configuring default language options in a site

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-86798](https://issues.liferay.com/browse/LPS-86798).<br><br>Hey Sam, can you do a peer review of this change to make sure I didn't miss anything?@pei-jung @stsquared99 @alee8888 @crodriguezy

### CODE REVIEW

**Comment by drewbrokke** [comment]
@crodriguezy please see my changes at deca561.  We needed to also cover the case where user tried to save custom locales, which would still contain illegal locales and still have an error.  The approach I used instead was to make sure that the "customLocales" input never contained illegal locales.  So when we retrieve the group's locales, we iterate over the list and filter out any that are not contained in the available company locales.  Please let me know if you have any questions about this - I know it altered your code significantly.

**Comment by stsquared99** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/64724. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by crodriguezy** [comment]
Hi @drewbrokke , thanks for reviewing this so quick.

I thought the way the customaLocales' configuration was implemented was ok, since the message error is already warning the user to remove manually from the list those languages which are not currently available in the company.
If I understand well, with your solution no error will ever show up in the page, [this code](https://github.com/liferay/liferay-portal/blob/c093329817098a0494c178fc4508d32a0a9a9bd2/modules/apps/site/site-admin-web/src/main/resources/META-INF/resources/site/display_settings.jsp#L107) will be never executed then. So, the [validation done in the backend](https://github.com/liferay/liferay-portal/blob/c093329817098a0494c178fc4508d32a0a9a9bd2/portal-impl/src/com/liferay/portal/service/impl/GroupLocalServiceImpl.java#L5094) of the new languages to be configured will have no sense. Am I right?

Additionaly, I should mention that during my tests I confirmed that if a language is removed from the instance and a web content is created from the site, the (removed) translation is shown for 
this WC because the site still has it. Which is a contradiction with the fact that you don't show it in the left list of the custom languages configuration of the site.

If you filter out those locales without the user knowing it, it could be a bit confusing for him and he will not know that the company locales have changed. Instead, if we warn him to remove manually them, he will realize something has changed and will act accordingly (maybe not only in this section).

Please let me know if I have missed anything or if you have any comments related to my conclusions.

Thank you again!

**Comment by drewbrokke** [comment]
Hi @crodriguezy!  Thank you for your explanation. It makes sense that my approach could cause confusion to the end user since they will see a discrepancy between what language are available for something like web content and what they see in Site Configuration.

In that case, I think your solution is the better approach.  I will send a pull reverting my changes in master.

**Pull request closed without merging**
