### PR TITLE
LPS-99263

### PR DESCRIPTION
**Pull request by Preston-Crary**
Can you double check I didn't break anything?

Thanks

### CODE REVIEW

**Comment by stsquared99** [comment]
Just started reviewing :)

**Comment by stsquared99** [comment]
@Preston-Crary Looks good, shall I send it through?

**Comment by Preston-Crary** [comment]
Yes, go ahead and send it to Brian. Thanks!

**Comment by stsquared99** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/77308.

**Pull request closed without merging**
