### PR TITLE
LPS-90144 Convert "delete remaining data" view to "delete nonreviewable data" tab

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-90144](https://issues.liferay.com/browse/LPS-90144).<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by drewbrokke** [comment]
Hey @stsquared99 can you double-check my changes?  If they look good go ahead and send to Brian.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
Just started reviewing :)

**Comment by stsquared99** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/67853.

**Pull request closed without merging**
